# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  game_config = debug
  assimp_config = debug

else ifeq ($(config),release)
  game_config = release
  assimp_config = release

else ifeq ($(config),dist)
  game_config = dist
  assimp_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := game assimp

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

game: assimp
ifneq (,$(game_config))
	@echo "==== Building game ($(game_config)) ===="
	@${MAKE} --no-print-directory -C . -f game.make config=$(game_config)
endif

assimp:
ifneq (,$(assimp_config))
	@echo "==== Building assimp ($(assimp_config)) ===="
	@${MAKE} --no-print-directory -C thirdparty/assimp -f Makefile config=$(assimp_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f game.make clean
	@${MAKE} --no-print-directory -C thirdparty/assimp -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   game"
	@echo "   assimp"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"